<?php
# Filename:	lib_db.php
# Description: Database wrapper
# Usage:
#	$oConn = new Connect;
#	$sSQL = "SELECT iCatID, sCat FROM category";
#	$aResultSet = $oConn->Query($sSQL);
#	
#	echo "<pre>";
#	print_r($aResultSet);
#	echo "</pre>";
#	
#	for ($x=0; $x<$oConn->NumRows(); $x++){
#		echo $aResultSet[$x]["iCatID"].". ".$aResultSet[$x]["sCat"]."<br />";
#	}
#	
#	$oConn->DBClose();

class Connect{
	var $oConn;
	var $oResult;
	
	var $_sMySQLServer;
	var $_sDBName;
	var $_sDBUser;
	var $_sDBPass;
	
	var $_sLastQuery;
	var $_iNumRows;
	var $_iAffectedRows;
	var $_iNumFields;
	var $_aData;
	var $_iLastID;
	var $_sError;
	
	function Connect($sMySQLServer=DB_SERVER, $sDBName=DB_DATABASE, $sDBUser=DB_SERVER_USERNAME, $sDBPass=DB_SERVER_PASSWORD){
		$this->_sMySQLServer = $sMySQLServer;
		$this->_sDBName = $sDBName;
		$this->_sDBUser = $sDBUser;
		$this->_sDBPass = $sDBPass;
		
		if (!$this->oConn = @mysql_connect($this->_sMySQLServer, $this->_sDBUser, $this->_sDBPass)){
			$sMySQLError = @mysql_error($this->oConn);
			$this->_sError = "Unable to connect to database: ".$this->_sMySQLServer.".<br /><em>".$sMySQLError."</em>";
			$this->DisplayErr($this->_sError);
		}else{
			if (!@mysql_select_db($this->_sDBName, $this->oConn)){
				$sMySQLError = @mysql_error($this->oConn);
				$this->_sError = "Unable to select database: ".$this->_sMySQLServer.".<br /><em>".$sMySQLError."</em>";
				$this->DisplayErr($this->_sError);
			}
		}
	}
	
	# Executes SELECT queries and returns the result set
	function Query($sSQLQuery){
		$this->_sLastQuery = $sSQLQuery;
		
		if (!$this->oResult = @mysql_query($sSQLQuery, $this->oConn)){
			$this->_sError = "Unable to perform query: ".$sSQLQuery.".<br /><em>".mysql_error($this->oConn)."</em>";
			$this->DisplayErr($this->_sError);
		}
		
		$this->_iNumRows = @mysql_num_rows($this->oResult);
		$this->_iNumFields = @mysql_num_fields($this->oResult);
		
		$aResulSet = array();
		$x = 0;
		
		while ($oRow = mysql_fetch_array($this->oResult, MYSQL_BOTH)){
			$aResulSet[$x] = $oRow;
			$x++;
		}
		
		$this->_aData = $aResulSet;
		
		mysql_free_result($this->oResult);
		
		return $this->_aData;
	}
	
	# Returns False for fail, True for success. Use for INSERT, UPDATE, DELETE queries
	function Execute($sSQL){
		$this->_sLastQuery = $sSQL;
		
        @mysql_unbuffered_query($sSQL, $this->oConn);
		$this->_iAffectedRows = @mysql_affected_rows($this->oConn);
		
		if (mysql_errno($this->oConn) == 0){
			if (substr(trim($this->_sLastQuery), 0, 6) == "INSERT") $this->_iLastID = @mysql_insert_id($this->oConn);
			return true;
		}else{
			$this->_sError = mysql_error($this->oConn);
			return false;
		}
	}
	
	# Returns the 1st field only
	function Scalar($sSQL){
		$aResultSet = $this->Query($sSQL);
		
		return ($this->_iNumRows > 0) ? $aResultSet[0][0]:0;
	}
	
	# Returns the Number of Rows based on a SELECT query
	function NumRows(){
		return $this->_iNumRows;
	}
	
	# Returns the Last ID of an INSERT query
	function LastID(){
		return (substr(trim($this->_sLastQuery), 0, 6) == "INSERT") ? $this->_iLastID:0;
	}
	
	# Returns the Number of Affected Rows of INSERT, UPDATE, DELETE queries
	function AffectedRows(){
		return $this->_iAffectedRows;
	}
	
	# Returns the Error Message generated by mysql_error()
	function ErrMsg(){
		return $this->_sError;
	}
	
	# Closes the database connection
	function DBClose(){
		mysql_close($this->oConn);
	}
	
	# Displays the error message
	function DisplayErr($sErr) {
		echo "<font face=\"Arial\" size=\"4\" color=\"red\"><b>System Halt</b></font>";
		echo "<hr /><font face=\"Verdana\" size=\"2\">";
		echo date('r');
		echo "<br />Error encountered during the process<br />";
		echo "The reported error was <font color=\"red\">".$sErr."</font>\n<br /><br />";
		echo ($this->_sLastQuery != "") ? "SQL:<br />".$this->_sLastQuery."<br /><br />":"";
		echo "If the problem persist, ";
		echo "contact <a href=\"mailto:mars@interactiveplusonline.com?subject=(".$_SERVER['SCRIPT_NAME'].") ".$sErr."\">Web Master</a> and report the problem.</font>";
		echo "<hr>";
		echo "<font face=\"Arial\" style=\"font-size:11px\">Developed by I-Active Plus Technologies, Inc.</font>";
		die;
	}
}
?>